# Generated by Django 4.2.6 on 2024-04-12 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QlyDiemApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('midtermScore', models.FloatField()),
                ('midtermPercen', models.FloatField(blank=True, null=True)),
                ('endtermScore', models.FloatField()),
                ('endtermPercen', models.FloatField(blank=True, null=True)),
                ('overallScore', models.FloatField()),
                ('result', models.CharField(max_length=100)),
                ('locked', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QlyDiemApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('score', models.FloatField()),
                ('scorePercen', models.FloatField(blank=True, null=True)),
                ('mainScore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QlyDiemApp.mainscore')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
