# Generated by Django 4.2.6 on 2024-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QlyDiemApp', '0002_mainscore_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainscore',
            name='endtermScore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainscore',
            name='midtermScore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainscore',
            name='overallScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
